# Capstone Project-Car accident severity (Week 2)

Applied Data Science Capstone by IBM/Coursera

In [5]:
import pandas as pd
import numpy as np

In [6]:
print("Hello Capstone Project Course!")

Hello Capstone Project Course!


# Introduction/Business Understanding

In this project we are going to predict the severity of an accident given the current weather, road and visibility conditions.Our predictor or target variable will be 'SEVERITYCODE' because it is used measure the severity of an accident from 0 to 5 within the dataset. Attributes used to weigh the severity of an accident are 'WEATHER', 'ROADCOND' and 'LIGHTCOND' .

# DATA

The predictor variable will be 'SEVERITYCODE' because it is used measure the severity of an accident  within the dataset. Attributes used to weigh the severity of an accident are 'WEATHER', 'ROADCOND' and 'LIGHTCOND'.The key features used for analysis are ‘SEVERITYVODE’,‘ADDRTYPE’, JUNCTIONTYPE’,‘WEATHER’, ‘ROADCOND’,‘LIGHTCOND’ ‘PERSONCOUNT’,‘PEDCOUNT’ ‘PEDCYLCOUNT’,’VEHCOUNT’    

In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [4]:
df=pd.read_csv("C:/Users/SIDNEY/Downloads/Data-Collisions.csv")

C:\Users\SIDNEY\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194673 entries, 0 to 194672
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype 
---  ------          --------------   ----- 
 0   SEVERITYCODE    194673 non-null  int64 
 1   ADDRTYPE        192747 non-null  object
 2   PERSONCOUNT     194673 non-null  int64 
 3   PEDCOUNT        194673 non-null  int64 
 4   PEDCYLCOUNT     194673 non-null  int64 
 5   VEHCOUNT        194673 non-null  int64 
 6   JUNCTIONTYPE    188344 non-null  object
 7   INATTENTIONIND  29805 non-null   object
 8   UNDERINFL       189789 non-null  object
 9   WEATHER         189592 non-null  object
 10  ROADCOND        189661 non-null  object
 11  LIGHTCOND       189503 non-null  object
 12  SPEEDING        9333 non-null    object
dtypes: int64(5), object(8)
memory usage: 19.3+ MB


In [5]:
df.drop(['X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY',
       'REPORTNO', 'STATUS', 'INTKEY', 'LOCATION',
       'EXCEPTRSNCODE', 'EXCEPTRSNDESC', 'SEVERITYCODE.1', 'SEVERITYDESC',
       'COLLISIONTYPE','INCDATE','INCDTTM','SDOT_COLCODE',
       'SDOT_COLDESC','PEDROWNOTGRNT', 'SDOTCOLNUM',
       'ST_COLCODE', 'ST_COLDESC', 'SEGLANEKEY', 'CROSSWALKKEY',
       'HITPARKEDCAR','INATTENTIONIND','SPEEDING'],axis=1,inplace=True)

In [6]:
df.columns.values

array(['SEVERITYCODE', 'ADDRTYPE', 'PERSONCOUNT', 'PEDCOUNT',
       'PEDCYLCOUNT', 'VEHCOUNT', 'JUNCTIONTYPE', 'UNDERINFL', 'WEATHER',
       'ROADCOND', 'LIGHTCOND'], dtype=object)

In [10]:
df.head(6)

SEVERITYCODE      ADDRTYPE  PERSONCOUNT  PEDCOUNT  PEDCYLCOUNT  VEHCOUNT  \
0             2  Intersection            2         0            0         2   
1             1         Block            2         0            0         2   
2             1         Block            4         0            0         3   
3             1         Block            3         0            0         3   
4             2  Intersection            2         0            0         2   
5             1  Intersection            2         0            0         2   

                              JUNCTIONTYPE UNDERINFL   WEATHER ROADCOND  \
0   At Intersection (intersection related)         N  Overcast      Wet   
1  Mid-Block (not related to intersection)         0   Raining      Wet   
2  Mid-Block (not related to intersection)         0  Overcast      Dry   
3  Mid-Block (not related to intersection)         N     Clear      Dry   
4   At Intersection (intersection related)         0   Raining      Wet   
5   At Intersection (intersection related)         N     Clear      Dry   

                 LIGHTCOND  
0                 Daylight  
1  Dark - Street Lights On  
2                 Daylight  
3                 Daylight  
4                 Daylight  
5                 Daylight

In [15]:
df.dropna(inplace=True)

In [32]:
df.corr()

SEVERITYCODE  PERSONCOUNT  PEDCOUNT  PEDCYLCOUNT  VEHCOUNT
SEVERITYCODE      1.000000     0.124513  0.245618     0.214265 -0.081325
PERSONCOUNT       0.124513     1.000000 -0.027206    -0.042768  0.399650
PEDCOUNT          0.245618    -0.027206  1.000000    -0.018730 -0.317280
PEDCYLCOUNT       0.214265    -0.042768 -0.018730     1.000000 -0.307744
VEHCOUNT         -0.081325     0.399650 -0.317280    -0.307744  1.000000

In [52]:
df_new=df[['SEVERITYCODE', 'ADDRTYPE', 'JUNCTIONTYPE', 'WEATHER','ROADCOND', 'LIGHTCOND']]

In [55]:
df_new

SEVERITYCODE      ADDRTYPE                             JUNCTIONTYPE  \
0                  2  Intersection   At Intersection (intersection related)   
1                  1         Block  Mid-Block (not related to intersection)   
2                  1         Block  Mid-Block (not related to intersection)   
3                  1         Block  Mid-Block (not related to intersection)   
4                  2  Intersection   At Intersection (intersection related)   
...              ...           ...                                      ...   
194668             2         Block  Mid-Block (not related to intersection)   
194669             1         Block  Mid-Block (not related to intersection)   
194670             2  Intersection   At Intersection (intersection related)   
194671             2  Intersection   At Intersection (intersection related)   
194672             1         Block  Mid-Block (not related to intersection)   

         WEATHER ROADCOND                LIGHTCOND  
0       Overcast      Wet                 Daylight  
1        Raining      Wet  Dark - Street Lights On  
2       Overcast      Dry                 Daylight  
3          Clear      Dry                 Daylight  
4        Raining      Wet                 Daylight  
...          ...      ...                      ...  
194668     Clear      Dry                 Daylight  
194669   Raining      Wet                 Daylight  
194670     Clear      Dry                 Daylight  
194671     Clear      Dry                     Dusk  
194672     Clear      Wet                 Daylight  

[182914 rows x 6 columns]

In [65]:
# Label Encoding
# Convert column to category
df_new["WEATHER"] = df_new["WEATHER"].astype('category')
df_new["ROADCOND"] = df_new["ROADCOND"].astype('category')
df_new["LIGHTCOND"] = df_new["LIGHTCOND"].astype('category')

# Assign variable to new column for analysis
df_new["WEATHER_CAT"] = df_new["WEATHER"].cat.codes
df_new["ROADCOND_CAT"] = df_new["ROADCOND"].cat.codes
df_new["LIGHTCOND_CAT"] = df_new["LIGHTCOND"].cat.codes

df_new.head(5)

C:\Users\SIDNEY\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\SIDNEY\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\SIDNEY\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try

SEVERITYCODE      ADDRTYPE                             JUNCTIONTYPE  \
0             2  Intersection   At Intersection (intersection related)   
1             1         Block  Mid-Block (not related to intersection)   
2             1         Block  Mid-Block (not related to intersection)   
3             1         Block  Mid-Block (not related to intersection)   
4             2  Intersection   At Intersection (intersection related)   

    WEATHER ROADCOND                LIGHTCOND  WEATHER_CAT  ROADCOND_CAT  \
0  Overcast      Wet                 Daylight            4             8   
1   Raining      Wet  Dark - Street Lights On            6             8   
2  Overcast      Dry                 Daylight            4             0   
3     Clear      Dry                 Daylight            1             0   
4   Raining      Wet                 Daylight            6             8   

   LIGHTCOND_CAT  
0              5  
1              2  
2              5  
3              5  
4              5

In [67]:
df_new["SEVERITYCODE"].value_counts()

1    126276
2     56638
Name: SEVERITYCODE, dtype: int64

In [68]:
df_new["WEATHER"].value_counts()


Clear                       109065
Raining                      32649
Overcast                     27189
Unknown                      11637
Snowing                        881
Other                          746
Fog/Smog/Smoke                 556
Sleet/Hail/Freezing Rain       112
Blowing Sand/Dirt               49
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

In [69]:
df_new["ROADCOND"].value_counts()

Dry               122159
Wet                46720
Unknown            11521
Ice                 1178
Snow/Slush           978
Other                123
Standing Water       108
Sand/Mud/Dirt         67
Oil                   60
Name: ROADCOND, dtype: int64

In [70]:
df_new["LIGHTCOND"].value_counts()


Daylight                    113850
Dark - Street Lights On      47550
Unknown                      10448
Dusk                          5772
Dawn                          2454
Dark - No Street Lights       1462
Dark - Street Lights Off      1157
Other                          210
Dark - Unknown Lighting         11
Name: LIGHTCOND, dtype: int64

# Balancing the Dataset

Our target variable SEVERITYCODE is only 42% balanced. In fact, severitycode in class 1 is nearly three times the size of class 2.

We can fix this by downsampling the majority class.



In [71]:
from sklearn.utils import resample

In [73]:
### Seperate majority and minority classes
df_new_majority = df_new[df_new.SEVERITYCODE==1]
df_new_minority = df_new[df_new.SEVERITYCODE==2]

#Downsample majority class
df_new_majority_downsampled = resample(df_new_majority,
                                        replace=False,
                                        n_samples=58188,
                                        random_state=123)

# Combine minority class with downsampled majority class
df_new_balanced = pd.concat([df_new_majority_downsampled, df_new_minority])

# Display new class counts
df_new_balanced.SEVERITYCODE.value_counts()

1    58188
2    56638
Name: SEVERITYCODE, dtype: int64

# Methodology

Our data is now ready to be fed into machine learning models.

We will use the following models:

### K-Nearest Neighbor (KNN)
KNN will help us predict the severity code of an outcome by finding the most similar to data point within k distance.



### Decision Tree
A decision tree model gives us a layout of all possible outcomes so we can fully analyze the consequences of a decision. It context, the decision tree observes all possible outcomes of different weather conditions.



### Logistic Regression
Because our dataset only provides us with two severity code outcomes, our model will only predict one of those two classes. This makes our data binary, which is perfect to use with logistic regression.

# Initialization

### Defining X and Y

In [76]:
import numpy as np
X = np.asarray(df_new_balanced[['WEATHER_CAT', 'ROADCOND_CAT', 'LIGHTCOND_CAT']])
X[0:5]

array([[ 1,  0,  5],
       [ 4,  0,  4],
       [ 6,  8,  2],
       [10,  7,  8],
       [ 4,  8,  5]], dtype=int8)

In [77]:
y = np.asarray(df_new_balanced['SEVERITYCODE'])
y [0:5]

array([1, 1, 1, 1, 1], dtype=int64)

### Nomalize the Data

In [78]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-0.71319926, -0.68047202,  0.42581955],
       [ 0.4355535 , -0.68047202, -0.19473248],
       [ 1.20138868,  1.52354205, -1.43583654],
       [ 2.73305903,  1.24804029,  2.28747564],
       [ 0.4355535 ,  1.52354205,  0.42581955]])

### Train/Test Split

We will use 30% of our data for testing and 70% for training.

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (80378, 3) (80378,)
Test set: (34448, 3) (34448,)


# K-Nearest Neighbors (KNN)

In [80]:
# Building the KNN Model
from sklearn.neighbors import KNeighborsClassifier

k = 25

In [81]:
#Train Model & Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

Kyhat = neigh.predict(X_test)
Kyhat[0:5]

array([2, 1, 2, 2, 2], dtype=int64)

## Decision Tree

In [88]:
# Building the Decision Tree
from sklearn.tree import DecisionTreeClassifier
df_newTree = DecisionTreeClassifier(criterion="entropy", max_depth = 7)
df_newTree
df_newTree.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [90]:
# Train Model & Predict
DTyhat = df_newTree.predict(X_test)


## Logistic Regration

In [91]:
# Building the LR Model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=6, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=6, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [92]:
# Train Model & Predicr
LRyhat = LR.predict(X_test)
LRyhat

array([1, 1, 2, ..., 1, 2, 2], dtype=int64)

In [93]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.54940819, 0.45059181],
       [0.52458009, 0.47541991],
       [0.45649265, 0.54350735],
       ...,
       [0.50632209, 0.49367791],
       [0.48136103, 0.51863897],
       [0.45649265, 0.54350735]])

# Results & Evaluation

Now we will check the accuracy of our models.

In [94]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

# K-Nearest Neighbor

In [95]:
# Jaccard Similarity Score
jaccard_similarity_score(y_test, Kyhat)


C:\Users\SIDNEY\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


0.5328611240130051

In [99]:
# F1-SCORE
f1_score(y_test, Kyhat, average='macro')


0.4921075848964933

Model is most accurate when k is 25.

# Decision Tree

In [97]:
# Jaccard Similarity Score
jaccard_similarity_score(y_test, DTyhat)

0.5465048769159313

In [98]:
# F1-SCORE
f1_score(y_test, DTyhat, average='macro')


0.5203507728191309

Model is most accurate with a max depth of 7.

# Logistic Regression

In [100]:
# Jaccard Similarity Score
jaccard_similarity_score(y_test, LRyhat)

0.5215977705527172

In [101]:
# F1-SCORE
f1_score(y_test, LRyhat, average='macro')


0.5097825024463251

In [102]:
# LOGLOSS
yhat_prob = LR.predict_proba(X_test)
log_loss(y_test, yhat_prob)

0.6868866924905638

Model is most accurate when hyperparameter C is 6.

# Discussion

In the beginning of this notebook, we had categorical data that was of type 'object'. This is not a data type that we could have fed through an algorithm, so label encoding was used to created new classes that were of type int8; a numerical data type.

After solving that issue we were presented with another - imbalanced data. As mentioned earlier, class 1 was nearly three times larger than class 2. The solution to this was downsampling the majority class with sklearn's resample tool. We downsampled to match the minority class exactly with 58188 values each.

Once we analyzed and cleaned the data, it was then fed through three ML models; K-Nearest Neighbor, Decision Tree and Logistic Regression. Although the first two are ideal for this project, logistic regression made the most sense because of its binary nature.

Evaluation metrics used to test the accuracy of our models were jaccard index, f-1 score and logloss for logistic regression. Choosing different k, max depth and hyperamater C values helped to improve our accuracy to be the best possible.

# Conclusion

Based on historical data from weather conditions pointing to certain classes, we can conclude that particular weather conditions have a somewhat impact on whether or not travel could result in property damage (class 1) or injury (class 2).